### ISSUE TITLE
 Data encoded as hex and passed on the command line must have a length that is a multiple of 2

### ISSUE THREAD

**Issue by nBp1Ng** [NickstaDB/SerializationDumper#13]
Hello,

  There is a questions when i enter a hex-ascii encoded byte string , "Error: Data encoded as hex and passed on the command line must have a length that is a multiple of 2." is displayed in cmd ，but i enter a hex-ascii encoded byte string he remainder of 2 is equal to 0.

**Comment by NickstaDB** [comment]
This was fixed in the source but I hadn't published a build. Here you go https://github.com/NickstaDB/SerializationDumper/releases/download/1.13/SerializationDumper-v1.13.jar
