### ISSUE TITLE
Bailing out too early for SC_EXTERNALIZABLE?

### ISSUE THREAD

**Issue by DiputsMonro** [NickstaDB/SerializationDumper#15]
https://github.com/NickstaDB/SerializationDumper/blob/49dbece69f0b8230aaed4a0c50ca56fecc9376c0/src/nb/deser/SerializationDumper.java#L859-L867

In the code section above in readClassData, we appear to be looping over all classes in the hierarchy and bailing out if any of them have SC_EXTERNALIZABLE, assuming that they cannot be parsed.  But:

1) Aren't we able to parse a class if both SC_EXTERNALIZABLE and SC_BLOCK_DATA are set?  It looks like there is even a condition for this on line 894.

2) Isn't it possible that some superclasses in the hierarchy are not externalizable?  Perhaps this check should be moved inside the for loop below so that we can dump information about the valid superclasses and fields until we actually hit a class that can't be parsed.

Let me know if there's a mistake in my understanding.

**Comment by NickstaDB** [comment]
What's the issue here? Can you provide sample data, or preferably code to generate sample data, that demonstrates the issue at hand?

**Comment by NickstaDB** [comment]
I believe this is fixed thanks to @Marcono1234 (see #19), but let me know if you're still having any related issues with the latest code.
